[package]
name = "todo-cli"
version = "0.0.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

[lib]
name = "lib"
path = "src/lib/mod.rs"
